TABLE1_COLUMNS = [
    "Metal Symbol",
    "Sample ID",
    "Synthesis Method",
    "Treatment",
    "Initial Temperature (K)",
    "Quasi-static Yield Stress (MPa)",
    "Free Surface Velocity at HEL (m/s)",
    "Shear Stress at HEL (GPa)",
    "Hardness",
    "Bulk Modulus (GPa)",
    "Shear Modulus (GPa)",
    "Young's Modulus (GPa)",
    "Poisson's Ratio",
    "Melting Point (K)",
    "Sample Thickness (mm)",
    "Sample Diameter (mm)",
    "Grain Size (µm)",
    "Initial Density (g/cm³)",
    "Longitudinal Sound Speed (m/s)",
    "Shear Sound Speed (m/s)",
    "Bulk Sound Speed (m/s)",
    "Flyer Material Name",
    "Flyer Material Code",
    "Flyer Thickness (mm)",
    "Flyer Diameter (mm)",
    "Impact Velocity (m/s)",
    "Longitudinal Stress at HEL (GPa)",
    "Peak Stress / Hugoniot Stress (GPa)",
    "Strain Rate (s⁻¹)",
    "Pulse Duration (µs)",
    "Experiment Type",
    "Gas Gun Diameter (mm)",
    "Spall Strength (GPa)",
    "Spall Pullback Velocity (m/s)",
    "Reference Title",
    "DOI",
    "Verification",
]
